### ISSUE TITLE
local pc environment is annoying

### ISSUE THREAD

**Issue by wanghaisheng** [SKbarbon/fpyo2ipa#1]
```
name: Build App
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "V*"

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows, macos]
        include:
        - build: linux
          os: ubuntu-20.04
          rust: stable
          target: x86_64-unknown-linux-musl
        - build: windows
          os: windows-latest
          rust: stable-x86_64-msvc
          target: x86_64-pc-windows-msvc
        - build: macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"


    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        pip install -r dev.txt
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get update      
        python -m pip install --upgrade pip
        pip install -r dev.txt        

      if: matrix.os == 'macos-latest'
      run: |
        python -m pip install --upgrade pip
        pip install -r dev.txt        



    - name: build for Ubuntu
      if: matrix.os == 'ubuntu-20.04'
      run: flet pack main.py --name flet-saas-starter --icon icon.png --product-name flet-saas-starter --product-version "0.1.0" --copyright "Copyright (c) 2022 TiktokaStudio Inc."


    - name: build for MacOS
      if: matrix.os == 'macos-latest'
      run: |
        flet pack main.py --name flet-saas-starter --icon icon.png --product-name flet-saas-starter --product-version "0.1.0" --copyright "Copyright (c) 2022 TiktokaStudio Inc."


    - name: build for windows
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        flet pack main.py --name flet-saas-starter --icon icon.png --product-name flet-saas-starter --product-version "0.1.0" --copyright "Copyright (c) 2022 TiktokaStudio Inc."

    - name: build for ios
      if: matrix.os == 'macos-latest'
      run: |
        flet publish main.py 
        python3 -m venv venv
        source venv/bin/activate      
        pip install fpyo2apk --upgrade
        python3 -m fpyo2ipa.build --name flet-saas-starter  --copyright "Copyright (c) 2022 TiktokaStudio Inc."



    - name: build for android
      if: matrix.os == 'macos-latest'
      run: |
        flet publish main.py 
        python3 -m venv venv
        source venv/bin/activate  
        pip install fpyo2ipa --upgrade
      
        python3 -m fpyo2apk.build --name flet-saas-starter  --copyright "Copyright (c) 2022 TiktokaStudio Inc."


    - name: Upload files
      # arg info: https://github.com/ncipollo/release-action#release-action
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "output/*/*.*"
        token: ${{ secrets.GITHUB_TOKEN }}

```

can you help me with this github action yml
